[package]
name = "picolink"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
serialport = "4.2"
num-traits = "0.2"
num-derive = "0.4"