[package]
name = "picolink"
version = "1.7.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
num-traits = "0.2"
num-derive = "0.4"
dirs = "5.0"
serialport = { version = "4", default-features = false }

