name: Firmware CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'firmware/**'
      - '.github/workflows/firmware.yml'
  pull_request:
    paths:
      - 'firmware/**'
      - '.github/workflows/firmware.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout SDK
        run: |
          git clone https://github.com/raspberrypi/pico-sdk.git --branch master
          cd pico-sdk
          git submodule update --init
      - name: Setup Build Dependencies
        run: sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib
      - name: Build
        run: |
          mkdir build
          cd build
          export PICO_SDK_PATH=../pico-sdk
          cmake ../firmware
          make
      - uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            build/PicoROM.elf
            build/PicoROM.uf2
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [build]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: firmware
      - name: Attach firmware
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: PicoROM*

