name: PicoROM Tool CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'host/**'
      - '.github/workflows/tool.yml'

  pull_request:
    paths:
      - 'host/**'
      - '.github/workflows/tool.yml'

  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: '${{ github.token }}'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            host: macos-latest
            cross: false
          - target: x86_64-pc-windows-msvc
            host: windows-latest
            cross: false
          - target: aarch64-apple-darwin
            host: macos-latest
            cross: false
          - target: armv7-unknown-linux-musleabihf
            host: ubuntu-latest
            cross: true
          - target: x86_64-unknown-linux-musl
            host: ubuntu-latest
            cross: true
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo install cross --git https://github.com/cross-rs/cross
        if: ${{ matrix.cross }}
      - run: cross build --release --target ${{ matrix.target }} --manifest-path host/picorom/Cargo.toml --target-dir target
        if: ${{ matrix.cross }}
      - run: cargo build --release --target ${{ matrix.target }} --manifest-path host/picorom/Cargo.toml --target-dir target
        if: ${{ !matrix.cross }}
      - run: |
          mkdir artifacts
          cp target/${{ matrix.target }}/release/picorom.exe artifacts/picorom-${{ matrix.target }}.exe
          cp target/${{ matrix.target }}/release/picorom.pdb artifacts/picorom-${{ matrix.target }}.pdb
        if: ${{ matrix.host == 'windows-latest' }}
      - run: |
          mkdir artifacts
          cp target/${{ matrix.target }}/release/picorom artifacts/picorom-${{ matrix.target }}
        if: ${{ matrix.host != 'windows-latest' }}
      - uses: actions/upload-artifact@v4
        with:
          name: picorom-${{ matrix.target }}
          path: artifacts/*
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [build]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup ARM toolchain
        run: sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib

      - name: Build firmware
        run: |
          mkdir build && cd build
          cmake ../firmware
          make
          make firmware-bundle.zip

      - uses: actions/download-artifact@v4
        with:
          pattern: picorom-*
          path: tools/
          merge-multiple: true

      - name: Bundle firmware into tools
        run: |
          for binary in tools/picorom-*; do
            # Skip .pdb files
            if [[ "$binary" == *.pdb ]]; then continue; fi
            cat "$binary" build/firmware-bundle.zip > "${binary}.bundled"
            mv "${binary}.bundled" "$binary"
            # Restore execute permission for non-Windows
            if [[ ! "$binary" == *.exe ]]; then chmod +x "$binary"; fi
          done

      - name: Upload tools to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: tools/picorom*

      - name: Upload firmware to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: build/PicoROM*.uf2

