name: PicoROM Tool CI

on:
  push:
    branches: [main]
    tags: ['*']
    paths:
      - 'host/**'
      - 'firmware/**'
      - '.github/workflows/tool.yml'
  pull_request:
    paths:
      - 'host/**'
      - 'firmware/**'
      - '.github/workflows/tool.yml'
  workflow_dispatch:

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: '${{ github.token }}'

jobs:
  build-firmware:
    name: Build Firmware
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup ARM toolchain
        run: sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libstdc++-arm-none-eabi-newlib
      - name: Build firmware
        run: |
          mkdir build && cd build
          cmake ../firmware
          make
          make firmware-bundle.zip
      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/PicoROM*.uf2
            build/firmware-bundle.zip
          if-no-files-found: error

  build:
    name: Build
    needs: [build-firmware]
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            host: macos-latest
            cross: false
          - target: x86_64-pc-windows-msvc
            host: windows-latest
            cross: false
          - target: aarch64-apple-darwin
            host: macos-latest
            cross: false
          - target: armv7-unknown-linux-musleabihf
            host: ubuntu-latest
            cross: true
          - target: x86_64-unknown-linux-musl
            host: ubuntu-latest
            cross: true
    runs-on: ${{ matrix.host }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - uses: actions/download-artifact@v4
        with:
          name: firmware
          path: host/picorom/
      - run: cargo install cross --git https://github.com/cross-rs/cross
        if: ${{ matrix.cross }}
      - name: Build with embedded firmware (cross)
        if: ${{ matrix.cross }}
        env:
          EMBED_FIRMWARE: firmware-bundle.zip
        run: cross build --release --target ${{ matrix.target }} --manifest-path host/picorom/Cargo.toml --target-dir target
      - name: Build with embedded firmware (native)
        if: ${{ !matrix.cross }}
        env:
          EMBED_FIRMWARE: firmware-bundle.zip
        run: cargo build --release --target ${{ matrix.target }} --manifest-path host/picorom/Cargo.toml --target-dir target
      - name: Write signing key
        if: ${{ contains(matrix.target, 'apple-darwin') }}
        env:
          SIGNING_KEY_PEM: ${{ secrets.SIGNING_KEY_PEM }}
        run: |
          echo $SIGNING_KEY_PEM | base64 -d > key.pem
      - name: Sign macOS binary
        if: ${{ contains(matrix.target, 'apple-darwin') }}
        uses: indygreg/apple-code-sign-action@v1
        with:
          input_path: target/${{ matrix.target }}/release/picorom
          sign_args: "-vvvv"
          pem_file: |
            key.pem
            cert.pem
      - name: Clean up signing key
        if: ${{ contains(matrix.target, 'apple-darwin') }}
        run: rm -f key.pem
      - run: |
          mkdir artifacts
          cp target/${{ matrix.target }}/release/picorom.exe artifacts/picorom-${{ matrix.target }}.exe
          cp target/${{ matrix.target }}/release/picorom.pdb artifacts/picorom-${{ matrix.target }}.pdb
        if: ${{ matrix.host == 'windows-latest' }}
      - run: |
          mkdir artifacts
          cp target/${{ matrix.target }}/release/picorom artifacts/picorom-${{ matrix.target }}
        if: ${{ matrix.host != 'windows-latest' }}
      - uses: actions/upload-artifact@v4
        with:
          name: picorom-${{ matrix.target }}
          path: artifacts/*
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: picorom-*
          path: tools/
          merge-multiple: true
      - uses: actions/download-artifact@v4
        with:
          name: firmware
          path: firmware/
      - name: Upload tools to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: tools/picorom*
      - name: Upload firmware to release
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: firmware/PicoROM*.uf2
